### ISSUE TITLE
Render Crash

### ISSUE THREAD

**Issue by Toilet-Man** [ichttt/FirstAid#126]
Game crashes every time I take damage, love your mod btw <3

```
[19May2021 16:08:04.974] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Framebuffer created: dfb
[19May2021 16:08:09.107] [SoundControl Sound Processor/WARN] [SoundControl/SoundFXProcessor]: SoundControl Sound Processor is lagging; behind 131 msecs
[19May2021 16:08:12.994] [SoundControl Sound Processor/WARN] [SoundControl/SoundFXProcessor]: SoundControl Sound Processor is lagging; behind 130 msecs
[19May2021 16:08:13.556] [SoundControl Sound Processor/WARN] [SoundControl/SoundFXProcessor]: SoundControl Sound Processor is lagging; behind 41 msecs
[19May2021 16:08:13.813] [SoundControl Sound Processor/WARN] [SoundControl/SoundFXProcessor]: SoundControl Sound Processor is lagging; behind 55 msecs
[19May2021 16:08:14.535] [SoundControl Sound Processor/WARN] [SoundControl/SoundFXProcessor]: SoundControl Sound Processor is lagging; behind 23 msecs
[19May2021 16:08:18.131] [SoundControl Sound Processor/WARN] [SoundControl/SoundFXProcessor]: SoundControl Sound Processor is lagging; behind 3 msecs
[19May2021 16:08:25.721] [SoundControl Sound Processor/WARN] [SoundControl/SoundFXProcessor]: SoundControl Sound Processor is lagging; behind 23 msecs
[19May2021 16:08:45.433] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 5
	Listeners:
		0: NORMAL
		1: ASM: class hunternif.mc.impl.atlas.forge.ForgeEvent in(Lnet/minecraftforge/client/event/RenderGameOverlayEvent$Pre;)V
		2: ASM: class com.stereowalker.survive.client.events.RenderOverlayEvents renderGameOverlay2(Lnet/minecraftforge/client/event/RenderGameOverlayEvent$Pre;)V
		3: ASM: class com.oblivioussp.spartanweaponry.event.HudEventHandler onRenderOverlayPre(Lnet/minecraftforge/client/event/RenderGameOverlayEvent$Pre;)V
		4: net.minecraftforge.eventbus.EventBus$$Lambda$3040/1214769003@6c8071cb
		5: net.minecraftforge.eventbus.EventBus$$Lambda$3040/1214769003@3762b6ec
		6: ASM: class com.minecraftabnormals.endergetic.client.events.OverlayEvents renderOverlays(Lnet/minecraftforge/client/event/RenderGameOverlayEvent$Pre;)V
		7: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@7dabf278 onOverlayRender(Lnet/minecraftforge/client/event/RenderGameOverlayEvent$Pre;)V
		8: ASM: class com.minecraftabnormals.upgrade_aquatic.client.render.gui.RenderOverlays renderScuteOverAir(Lnet/minecraftforge/client/event/RenderGameOverlayEvent$Pre;)V
		9: ASM: class com.simibubi.create.foundation.utility.placement.PlacementHelpers onRender(Lnet/minecraftforge/client/event/RenderGameOverlayEvent$Pre;)V
		10: ASM: vectorwing.farmersdelight.client.gui.NourishedHungerOverlay@1a3504b8 onPreRender(Lnet/minecraftforge/client/event/RenderGameOverlayEvent$Pre;)V
		11: ASM: de.maxhenkel.camera.ClientEvents@7a6c71f3 renderOverlay(Lnet/minecraftforge/client/event/RenderGameOverlayEvent$Pre;)V
		12: ASM: class ichttt.mods.firstaid.client.ClientEventHandler preRender(Lnet/minecraftforge/client/event/RenderGameOverlayEvent$Pre;)V
		13: ASM: class com.stereowalker.survive.client.events.RenderOverlayEvents renderGameOverlay(Lnet/minecraftforge/client/event/RenderGameOverlayEvent;)V
		14: ASM: class com.minecraftabnormals.upgrade_aquatic.client.render.gui.RenderOverlays renderOverlays(Lnet/minecraftforge/client/event/RenderGameOverlayEvent;)V
		15: LOW
		16: ASM: artifacts.common.item.HeliumFlamingoItem$ClientEventHandler@3cdba6ca render(Lnet/minecraftforge/client/event/RenderGameOverlayEvent$Pre;)V
		17: ASM: squeek.appleskin.client.HUDOverlayHandler@2ca670b2 onPreRender(Lnet/minecraftforge/client/event/RenderGameOverlayEvent$Pre;)V
		18: LOWEST
		19: ASM: dev.gigaherz.hudcompass.client.HudOverlay@3e0cf3b6 preOverlay(Lnet/minecraftforge/client/event/RenderGameOverlayEvent$Pre;)V
java.lang.NullPointerException
	at com.yungnickyoung.minecraft.betterportals.client.OverlayRenderer.lambda$renderReclaimerOverlay$1(OverlayRenderer.java:144)
	at com.yungnickyoung.minecraft.betterportals.client.OverlayRenderer$$Lambda$20043/1760501156.accept(Unknown Source)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165)
	at com.yungnickyoung.minecraft.betterportals.client.OverlayRenderer.renderReclaimerOverlay(OverlayRenderer.java:124)
	at com.yungnickyoung.minecraft.betterportals.client.ClientModule$$Lambda$8320/1204446362.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus$$Lambda$3040/1214769003.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2641/220942845.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.client.gui.ForgeIngameGui.pre(ForgeIngameGui.java:828)
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:121)
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:765)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$497/322505366.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

[19May2021 16:08:45.440] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID b1f2d3dd-6c3e-4c86-9472-bc95fcf62416
[19May2021 16:08:45.443] [Render thread/FATAL] [net.minecraft.client.Minecraft/]: Unreported exception thrown!
java.lang.NullPointerException: null
	at com.yungnickyoung.minecraft.betterportals.client.OverlayRenderer.lambda$renderReclaimerOverlay$1(OverlayRenderer.java:144) ~[?:1.16.4-0.3.2]
	at com.yungnickyoung.minecraft.betterportals.client.OverlayRenderer$$Lambda$20043/1760501156.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165) ~[?:?]
	at com.yungnickyoung.minecraft.betterportals.client.OverlayRenderer.renderReclaimerOverlay(OverlayRenderer.java:124) ~[?:1.16.4-0.3.2]
	at com.yungnickyoung.minecraft.betterportals.client.ClientModule$$Lambda$8320/1204446362.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3040/1214769003.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2641/220942845.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.client.gui.ForgeIngameGui.pre(ForgeIngameGui.java:828) ~[?:?]
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:121) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:765) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.23.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$497/322505366.call(Unknown Source) [forge-1.16.5-36.1.23.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[19May2021 16:08:52.819] [Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 7368ms or 147 ticks behind
[19May2021 16:08:52.856] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[19May2021 16:08:52.856] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[19May2021 16:08:52.866] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Toilet_Lord lost connection: Disconnected
[19May2021 16:08:52.866] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Toilet_Lord left the game
[19May2021 16:08:52.879] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Stopping singleplayer server as player logged out
[19May2021 16:08:52.879] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[19May2021 16:08:52.879] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Work plzplzplzplz]'/minecraft:overworld
```

**Comment by ichttt** [comment]
That crash you send is happens in the code of a mod named betterportals, and I also see optifine installed. Most likely one of these mods caused the crash. Try removing them and see if the issue still occures

**Comment by ichttt** [comment]
As said earlier, Problem with betterportals. Closing
