### ISSUE TITLE
First Aid Crashes Server

### ISSUE THREAD

**Issue by Tyv097** [ichttt/FirstAid#220]
server runs fine after removing first aid and configs
2023-12-20 17:47:17,049 main WARN Advanced terminal features are not available in this environment
[17:47:17] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 43.3.5, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, nogui]
[17:47:17] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 21.0.1 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[17:47:19] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Tyler/Desktop/Forge%20Server/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2363!/ Service=ModLauncher Env=SERVER
[17:47:20] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Tyler\Desktop\Forge Server\libraries\net\minecraftforge\fmlcore\1.19.2-43.3.5\fmlcore-1.19.2-43.3.5.jar is missing mods.toml file
[17:47:20] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Tyler\Desktop\Forge Server\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.3.5\javafmllanguage-1.19.2-43.3.5.jar is missing mods.toml file
[17:47:20] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Tyler\Desktop\Forge Server\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.3.5\lowcodelanguage-1.19.2-43.3.5.jar is missing mods.toml file
[17:47:20] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Tyler\Desktop\Forge Server\libraries\net\minecraftforge\mclanguage\1.19.2-43.3.5\mclanguage-1.19.2-43.3.5.jar is missing mods.toml file
[17:47:20] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select two dependency jars from JarJar which have the same identification: Mod File:  and Mod File: . Using Mod File:
[17:47:20] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 7 dependencies adding them to mods collection
[17:47:23] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[17:47:24] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
[17:47:24] [main/WARN] [mixin/]: Reference map 'vinery-forge-refmap.json' for vinery.mixins.json could not be read. If this is a development environment you can ignore this message
[17:47:24] [main/WARN] [mixin/]: Reference map 'jeitweaker.refmap.json' for jeitweaker.forge.mixins.json could not be read. If this is a development environment you can ignore this message
[17:47:24] [main/WARN] [mixin/]: Reference map 'jeitweaker.refmap.json' for jeitweaker.common.mixins.json could not be read. If this is a development environment you can ignore this message
[17:47:24] [main/WARN] [mixin/]: Reference map 'idas.refmap.json' for idas.mixins.json could not be read. If this is a development environment you can ignore this message
[17:47:24] [main/WARN] [mixin/]: Reference map 'simplyswords-common-refmap.json' for simplyswords-common.mixins.json could not be read. If this is a development environment you can ignore this message
[17:47:24] [main/WARN] [mixin/]: Reference map 'simplyswords-forge-refmap.json' for simplyswords.mixins.json could not be read. If this is a development environment you can ignore this message
[17:47:24] [main/WARN] [mixin/]: Reference map '${refmap_target}refmap.json' for corgilib.forge.mixins.json could not be read. If this is a development environment you can ignore this message
[17:47:24] [main/WARN] [mixin/]: Reference map 'mvs-forge-refmap.json' for mvs-forge.mixins.json could not be read. If this is a development environment you can ignore this message
[17:47:24] [main/INFO] [co.cu.Cupboard/]: Loaded config for: structureessentials.json
[17:47:25] [main/WARN] [mixin/]: Error loading class: vectorwing/farmersdelight/common/block/TomatoVineBlock (java.lang.ClassNotFoundException: vectorwing.farmersdelight.common.block.TomatoVineBlock)
[17:47:25] [main/WARN] [mixin/]: @Mixin target vectorwing.farmersdelight.common.block.TomatoVineBlock was not found supplementaries.mixins.json:CompatFarmersDelightMixin
[17:47:25] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/entity/PhantomRenderer (java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.PhantomRenderer)
[17:47:25] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.entity.PhantomRenderer was not found mixins.deeperdarker.json:PhantomRendererMixin
[17:47:26] [main/WARN] [mixin/]: Error loading class: net/bettercombat/client/collision/TargetFinder (java.lang.ClassNotFoundException: net.bettercombat.client.collision.TargetFinder)
[17:47:26] [main/WARN] [mixin/]: @Mixin target net.bettercombat.client.collision.TargetFinder was not found justleveling.mixins.json:MixTargetFinder
[17:47:26] [main/WARN] [mixin/]: Error loading class: noobanidus/mods/lootr/config/ConfigManager (java.lang.ClassNotFoundException: noobanidus.mods.lootr.config.ConfigManager)
[17:47:26] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.2.0-rc.5).
[17:47:27] [pool-2-thread-1/ERROR] [ne.mi.fm.lo.mo.BackgroundScanHandler/SCAN]: An error occurred scanning file Mod File: C:\Users\Tyler\Desktop\Forge Server\mods\firstaid-1.12.0.jar
java.util.concurrent.CompletionException: java.io.UncheckedIOException: java.util.zip.ZipException: invalid stored block lengths
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
        at java.lang.Thread.run(Thread.java:1583) [?:?] {}
Caused by: java.io.UncheckedIOException: java.util.zip.ZipException: invalid stored block lengths
        at cpw.mods.jarhandling.impl.Jar.verifyPath(Jar.java:180) ~[securejarhandler-2.1.4.jar:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModProvider.lambda$scanFile$0(AbstractJarFileModProvider.java:28) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
        at java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541) ~[?:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {}
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModProvider.scanFile(AbstractJarFileModProvider.java:30) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.ModFile.scanFile(ModFile.java:132) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:32) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:128) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
        ... 3 more
Caused by: java.util.zip.ZipException: invalid stored block lengths
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:181) ~[?:?] {}
        at java.io.InputStream.readNBytes(InputStream.java:412) ~[?:?] {}
        at java.io.InputStream.readAllBytes(InputStream.java:349) ~[?:?] {}
        at jdk.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:977) ~[jdk.zipfs:?] {}
        at jdk.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:870) ~[jdk.zipfs:?] {}
        at jdk.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:247) ~[jdk.zipfs:?] {}
        at java.nio.file.Files.newByteChannel(Files.java:379) ~[?:?] {}
        at java.nio.file.Files.newByteChannel(Files.java:431) ~[?:?] {}
        at cpw.mods.niofs.union.UnionFileSystem.byteChannel(UnionFileSystem.java:316) ~[securejarhandler-2.1.4.jar:?] {}
        at java.util.Optional.map(Optional.java:260) ~[?:?] {}
        at cpw.mods.niofs.union.UnionFileSystem.newReadByteChannel(UnionFileSystem.java:307) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.niofs.union.UnionFileSystemProvider.newByteChannel(UnionFileSystemProvider.java:149) ~[securejarhandler-2.1.4.jar:?] {}
        at java.nio.file.Files.newByteChannel(Files.java:379) ~[?:?] {}
        at java.nio.file.Files.newByteChannel(Files.java:431) ~[?:?] {}
        at java.nio.file.Files.readAllBytes(Files.java:3268) ~[?:?] {}
        at cpw.mods.jarhandling.impl.Jar.verifyPath(Jar.java:176) ~[securejarhandler-2.1.4.jar:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModProvider.lambda$scanFile$0(AbstractJarFileModProvider.java:28) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
        at java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541) ~[?:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {}
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModProvider.scanFile(AbstractJarFileModProvider.java:30) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.ModFile.scanFile(ModFile.java:132) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:32) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:128) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
        ... 3 more
[17:47:29] [main/WARN] [mixin/]: @Final field f_20945_:Ljava/util/Map; in vinery-common.mixins.json:LivingEntityMixin should be final
[17:47:33] [main/INFO] [minecraft/DataFixers]: Building unoptimized datafixer
[17:47:34] [main/WARN] [mixin/]: @ModifyConstant conflict. Skipping integrated_api.mixins.json:structures.StructurePoolMixin->@ModifyConstant::integrated_api_increaseWeightLimitDev(I)I with priority 1000, already redirected by yungsapi_forge.mixins.json:IncreaseStructureWeightLimitMixinForge->@ModifyConstant::yungsapi_increaseWeightLimit(I)I with priority 1000
[17:47:34] [main/INFO] [quark/]: TerraBlender not found, using injection method
[17:47:36] [main/WARN] [mixin/]: Mixin dungeons_mobs.mixins.json:MansionTemplateMixin has multiple constructors, (Lnet/minecraft/world/level/levelgen/structure/pieces/StructurePieceType;ILnet/minecraft/world/level/levelgen/structure/templatesystem/StructureTemplateManager;Lnet/minecraft/resources/ResourceLocation;Ljava/lang/String;Lnet/minecraft/world/level/levelgen/structure/templatesystem/StructurePlaceSettings;Lnet/minecraft/core/BlockPos;)V was selected

[17:47:36] [main/ERROR] [minecraft/Util]: Registry 'integrated_api:json_conditions' was empty after loading
[17:47:36] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
java.lang.RuntimeException: java.util.concurrent.CompletionException: java.io.UncheckedIOException: java.util.zip.ZipException: invalid stored block lengths
        at net.minecraftforge.fml.loading.moddiscovery.ModFile.getScanResult(ModFile.java:149) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:252) ~[fmlcore-1.19.2-43.3.5.jar%23318!/:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?] {}
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?] {}
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?] {}
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?] {}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:175) ~[fmlcore-1.19.2-43.3.5.jar%23318!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.19.2-43.3.5-universal.jar%23322!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23317!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.util.concurrent.CompletionException: java.io.UncheckedIOException: java.util.zip.ZipException: invalid stored block lengths
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
        at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
Caused by: java.io.UncheckedIOException: java.util.zip.ZipException: invalid stored block lengths
        at cpw.mods.jarhandling.impl.Jar.verifyPath(Jar.java:180) ~[securejarhandler-2.1.4.jar:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModProvider.lambda$scanFile$0(AbstractJarFileModProvider.java:28) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
        at java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541) ~[?:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModProvider.scanFile(AbstractJarFileModProvider.java:30) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.ModFile.scanFile(ModFile.java:132) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:32) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:128) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
        at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
Caused by: java.util.zip.ZipException: invalid stored block lengths
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:181) ~[?:?] {}
        at java.io.InputStream.readNBytes(InputStream.java:412) ~[?:?] {}
        at java.io.InputStream.readAllBytes(InputStream.java:349) ~[?:?] {}
        at jdk.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:977) ~[jdk.zipfs:?] {}
        at jdk.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:870) ~[jdk.zipfs:?] {}
        at jdk.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:247) ~[jdk.zipfs:?] {}
        at java.nio.file.Files.newByteChannel(Files.java:379) ~[?:?] {}
        at java.nio.file.Files.newByteChannel(Files.java:431) ~[?:?] {}
        at cpw.mods.niofs.union.UnionFileSystem.byteChannel(UnionFileSystem.java:316) ~[securejarhandler-2.1.4.jar:?] {}
        at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
        at cpw.mods.niofs.union.UnionFileSystem.newReadByteChannel(UnionFileSystem.java:307) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.niofs.union.UnionFileSystemProvider.newByteChannel(UnionFileSystemProvider.java:149) ~[securejarhandler-2.1.4.jar:?] {}
        at java.nio.file.Files.newByteChannel(Files.java:379) ~[?:?] {}
        at java.nio.file.Files.newByteChannel(Files.java:431) ~[?:?] {}
        at java.nio.file.Files.readAllBytes(Files.java:3268) ~[?:?] {}
        at cpw.mods.jarhandling.impl.Jar.verifyPath(Jar.java:176) ~[securejarhandler-2.1.4.jar:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModProvider.lambda$scanFile$0(AbstractJarFileModProvider.java:28) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
        at java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541) ~[?:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModProvider.scanFile(AbstractJarFileModProvider.java:30) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.ModFile.scanFile(ModFile.java:132) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:32) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:128) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
        at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
Press any key to continue . . .

**Comment by ichttt** [comment]
Looks like a broken jar/zip file. Try downloading the mod(s) again
