### ISSUE TITLE
Player is missing a damage model

### ISSUE THREAD

**Issue by badalanchik** [ichttt/FirstAid#233]
when a player dies, a crash occurs and the player crashes from the server

minecraft 1.19.2
forge 43.3.7
firstaid 1.12.0

I've included the full crash log below

[crash-2024-03-20_11.00.30-client.txt](https://github.com/ichttt/FirstAid/files/14669377/crash-2024-03-20_11.00.30-client.txt)

**Comment by superdude808** [comment]
the same issue is occurring in newer versions of the mod, specifically the 1.20.1 version 
[crash-2024-04-18_14.34.36-server.txt](https://github.com/ichttt/FirstAid/files/15020825/crash-2024-04-18_14.34.36-server.txt)

**Comment by killbot24** [comment]
Issue happens in 1.18.2 aswell

net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayerMixin.java:502) ~[server-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,xf:fml:xaeroworldmap:xaero_wm_serverplayer,xf:fml:xaerominimapfair:xaero_serverplayer,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,xf:fml:xaeroworldmap:xaero_wm_serverplayer,xf:fml:xaerominimapfair:xaero_serverplayer,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,xf:fml:xaeroworldmap:xaero_wm_serverplayer,xf:fml:xaerominimapfair:xaero_serverplayer,pl:mixin:APP:betterchunkloading.mixins.json:PlayerChunkDataMixin,pl:mixin:APP:mixins.arclight.core.json:world.entity.player.ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:hordes.mixin.json:MixinServerPlayer,pl:mixin:APP:forge-combatlog-common.mixins.json:ModDisconnectMixin,pl:mixin:APP:pluto.mixins.json:player.ServerPlayerMixin,pl:mixin:APP:puffish_skills.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:pehkui.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:customportalapi.mixins.json:ServerPlayerMixin,pl:mixin:APP:tac.mixins.json:common.ServerPlayerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerPlayerMixin_Optimize,pl:mixin:APP:securitycraft.mixins.json:camera.ServerPlayerMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerPlayNetHandlerMixin.java:207) ~[server-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(ConnectionMixin.java:245) ~[server-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:916) ~[server-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:forge-combatlog-common.mixins.json:ModTickMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:APP:pfm-common.mixins.json:PFMMixinDedicatedServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:forge-combatlog-common.mixins.json:ModTickMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2135) ~[server-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:forge-combatlog-common.mixins.json:ModTickMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:forge-combatlog-common.mixins.json:ModTickMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}
Caused by: java.lang.IllegalArgumentException: Player ranqur is missing a damage model!
	at ichttt.mods.firstaid.common.util.CommonUtils.lambda$getDamageModel$1(CommonUtils.java:143) ~[firstaid-1.11.1.jar%23148!/:1.11.1] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:281) ~[forge-1.18.2-40.2.14-universal.jar%23273!/:?] {re:mixin,re:classloading}
	at ichttt.mods.firstaid.common.util.CommonUtils.getDamageModel(CommonUtils.java:143) ~[firstaid-1.11.1.jar%23148!/:1.11.1] {re:classloading}
	at ichttt.mods.firstaid.common.damagesystem.distribution.HealthDistribution.distributeHealth(HealthDistribution.java:93) ~[firstaid-1.11.1.jar%23148!/:1.11.1] {re:classloading}
	at ichttt.mods.firstaid.common.EventHandler.onHeal(EventHandler.java:258) ~[firstaid-1.11.1.jar%23148!/:1.11.1] {re:classloading,pl:object_holder_definalize:A}
	at net.minecraftforge.eventbus.ASMEventHandler_904_EventHandler_onHeal_LivingHealEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%234!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%234!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%234!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onLivingHeal(ForgeEventFactoryMixin.java:529) ~[forge-1.18.2-40.2.14-universal.jar%23273!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.arclight.forge.json:ForgeEventFactoryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.entity.LivingEntity.m_5634_(LivingEntityMixin.java:979) ~[server-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_livingentity_addeffect,xf:fml:openpartiesandclaims:xaero_pac_livingentity_die,xf:fml:openpartiesandclaims:xaero_pac_livingentity_dropalldeathloot,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_livingentity_addeffect,xf:fml:openpartiesandclaims:xaero_pac_livingentity_die,xf:fml:openpartiesandclaims:xaero_pac_livingentity_dropalldeathloot,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin,pl:mixin:APP:saturn.mixins.json:allocations.fall_sounds.LivingEntityMixin,pl:mixin:APP:saturn.mixins.json:leaks.clear_memories.LivingEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:modernfix-forge.mixins.json:perf.forge_cap_retrieval.LivingEntityMixin,pl:mixin:APP:maxhealthfix.common.mixins.json:MixinLivingEntity,pl:mixin:APP:hordes.mixin.json:MixinLivingEntity,pl:mixin:APP:forge-combatlog-common.mixins.json:ModEntityDamageMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:puffish_skills.mixins.json:LivingEntityInvoker,pl:mixin:APP:puffish_skills.mixins.json:LivingEntityMixin,pl:mixin:APP:cgm.mixins.json:common.LivingEntityMixin,pl:mixin:APP:pehkui.mixins.json:LivingEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.compat1193minus.LivingEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.LivingEntityMixin,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityMixin,pl:mixin:APP:crittersandcompanions.mixins.json:LivingEntityMixin,pl:mixin:APP:cold_sweat.mixin.json:MixinEntityRiding,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:customportalapi.mixins.json:LivingEntityMixin,pl:mixin:APP:spacecatasb.mixins.json:MixinLivingEntity,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:tac.mixins.json:common.LivingEntityMixin,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:parcool.mixins.json:common.LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.entity.LivingEntityMixin_ActivationRange,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:APP:pehkui.mixins.json:compat115plus.LivingEntityMixin,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ApotheosisCompatMixin,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ObscureApiCompat,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at net.minecraft.world.effect.MobEffect.m_6742_(MobEffectMixin.java:46) ~[server-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:world.effect.MobEffectMixin,pl:mixin:A}
	at net.minecraft.world.effect.MobEffectInstance.m_19550_(MobEffectInstance.java:162) ~[server-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:potion,re:classloading,pl:accesstransformer:B,xf:fml:forge:potion,pl:mixin:APP:hordes.mixin.json:MixinMobEffectInstance,pl:mixin:APP:bookshelf.common.mixins.json:effect.AccessorMobEffectInstance,pl:mixin:APP:enhancedcelestials.mixins.json:access.EffectInstanceAccess,pl:mixin:A}
	at net.minecraft.world.effect.MobEffectInstance.m_19552_(MobEffectInstance.java:138) ~[server-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:potion,re:classloading,pl:accesstransformer:B,xf:fml:forge:potion,pl:mixin:APP:hordes.mixin.json:MixinMobEffectInstance,pl:mixin:APP:bookshelf.common.mixins.json:effect.AccessorMobEffectInstance,pl:mixin:APP:enhancedcelestials.mixins.json:access.EffectInstanceAccess,pl:mixin:A}
	
	Though just kicks from server with packet issue

**Comment by autumnly24** [comment]
I'm  experiencing the same issue still on 1.20.1.
I'm really hoping this gets fixed soon, this makes the game unplayable

**Comment by Untrustedlife** [comment]
Getting this too, playing not even on a server. It just crashes the game. 1.19.2, im thinking i'll downgrade to the old version of teh mod before i updated today as i havent seen it crash before updating.
edit:
Interesting , removing the default config fixed the crash and a huge hiccup at the start. So it actually has to do with specifying health for body parts in the default config. Is there a way around this?

**Comment by Untrustedlife** [comment]
I fixed this bug in my own Fork https://github.com/Untrustedlife/FirstAidCrashFix

**Comment by RemadeFuture** [comment]
@Untrustedlife anyway you can make a fork for 1.18.2 without the damage model error? I'd be very grateful. 
![image](https://github.com/ichttt/FirstAid/assets/46529923/5bbec43f-4ea4-4cdf-8692-72a75eda7e93)

**Comment by Kettle5000** [comment]
> I fixed this bug in my own Fork https://github.com/Untrustedlife/FirstAidCrashFix

Damn i also did one, 
https://github.com/Kettle5000/FirstAidFix1.20.1
In case anyone here is playing in 1.20.1 here it is.
Please it's just changing a singular line.

**Comment by Sussy-Chungus** [comment]
> > I fixed this bug in my own Fork https://github.com/Untrustedlife/FirstAidCrashFix
> 
> Damn i also did one, https://github.com/Kettle5000/FirstAidFix1.20.1 In case anyone here is playing in 1.20.1 here it is. Please it's just changing a singular line.

Hey man, total fucking noob here. How do I implement your fix? I'm running this mod on 1.20.1 and just got thrown this damage model error, too. Thanks for sharing your work btw :)

**Comment by ichttt** [comment]
I still did not find the actual root cause, but I've implemented a workaround. I will release a new version for 1.20.1 in the next few days that should hopefully mitigate the issue

**Comment by AofTHz** [comment]
It will only happened when receiving heal from any source AFTER player die and didn't respawn yet.
example: Regeneration Effect, Mod that heal you certain event(unsure)

that all I know
