### ISSUE TITLE
PlayerRevive API update

### ISSUE THREAD

**Issue by CreativeMD** [ichttt/FirstAid#41]
Hey there,
I have been working on PlayerRevive the past month and changed some stuff. It looks like it's compatible with the newest version of FirstAid:
```
java.lang.NoSuchMethodError: com.creativemd.playerrevive.api.IRevival.startBleeding()V
	at ichttt.mods.firstaid.common.util.CommonUtils.killPlayer(CommonUtils.java:47)
	at ichttt.mods.firstaid.common.damagesystem.distribution.DamageDistribution.handleDamageTaken(DamageDistribution.java:44)
	at ichttt.mods.firstaid.common.EventHandler.onLivingHurt(EventHandler.java:103)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_586_EventHandler_onLivingHurt_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:590)
```

If you want to I can create a pr to fix it.

In Regards,
CreativeMD

**Comment by ichttt** [comment]
Fixed in 3a6a364caf5fc42c8ba037f4b100e5fd586303b4
