### ISSUE TITLE
crashes on world load in 1.13.2

### ISSUE THREAD

**Issue by duntwave** [ichttt/FirstAid#47]
not sure what causes it but here's the log 

---- Minecraft Crash Report ----
// Why did you do that?

Time: 5/15/19 4:29 PM
Description: Exception in server tick loop

java.lang.VerifyError: Bad access to protected data in invokevirtual
Exception Details:
  Location:
    ichttt/mods/firstaid/common/DataManagerWrapper.func_187224_a(Lnet/minecraft/network/datasync/EntityDataManager$DataEntry;Lnet/minecraft/network/datasync/EntityDataManager$DataEntry;)V @6: invokevirtual
  Reason:
    Type 'net/minecraft/network/datasync/EntityDataManager' (current frame, stack[0]) is not assignable to 'ichttt/mods/firstaid/common/DataManagerWrapper'
  Current Frame:
    bci: @6
    flags: { }
    locals: { 'ichttt/mods/firstaid/common/DataManagerWrapper', 'net/minecraft/network/datasync/EntityDataManager$DataEntry', 'net/minecraft/network/datasync/EntityDataManager$DataEntry' }
    stack: { 'net/minecraft/network/datasync/EntityDataManager', 'net/minecraft/network/datasync/EntityDataManager$DataEntry', 'net/minecraft/network/datasync/EntityDataManager$DataEntry' }
  Bytecode:
    0x0000000: 2ab4 001f 2b2c b600 ffb1               

	at ichttt.mods.firstaid.common.EventHandler.registerCapability(EventHandler.java:147)
	at net.minecraftforge.eventbus.ASMEventHandler_18_EventHandler_registerCapability_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:266)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:573)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:567)
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:49)
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:45)
	at net.minecraft.entity.Entity.<init>(Entity.java:228)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:174)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:157)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:154)
	at net.minecraft.server.management.PlayerList.func_148545_a(PlayerList.java:405)
	at net.minecraft.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:113)
	at net.minecraft.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:64)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:769)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:669)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:115)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:565)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 556073080 bytes (530 MB) / 1342177280 bytes (1280 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:xaeroworldmap, mod:xaerominimap, mod:waterstrainer, mod:waila, mod:vulcanite, mod:uteamcore, mod:usefulbackpacks, mod:turtleshelldrop, mod:treechoppin, mod:torcherino, mod:tinymobfarm (incompatible), mod:thedragonlib, mod:structurecompass, mod:stairway, mod:ss, mod:simpleteleporters, mod:shulkertooltip (incompatible), mod:securitycraft, mod:searchablechests, mod:sdt, mod:ruins, mod:randompatches, mod:quickleafdecay, mod:pyramidplunder, mod:prettybeaches, mod:packingtape, mod:overpoweredarmorbar, mod:nofog, mod:modnametooltip, mod:lemonlib, mod:jph, mod:jmh, mod:jei, mod:ironchest, mod:harvest, mod:globalxp, mod:forgivingvoid, mod:forge, mod:followingvillagers (incompatible), mod:fleshtoleather, mod:firstaid (incompatible), mod:extraanvils, mod:exp_ore, mod:essentials, mod:engineersdecor, mod:enchdesc, mod:elevatorid, mod:controlling, mod:compressed_items, mod:charcoalblock, mod:caelus, mod:bowinfinityfix, mod:bno, mod:bettertitlescreen, mod:betteradvancements (incompatible), mod:armorplus, mod:appleskin, mod:animalnet, mod:ambientsounds
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by ichttt** [comment]
Wow. And nobody reported it until now...
