### ISSUE TITLE
Genetics Reborn Incompatibility

### ISSUE THREAD

**Issue by Villiy** [ichttt/FirstAid#71]
Hi,

Thanks for all of your work on this mod - it's been good until we started boosting ourselves (max hp) with Genetics Reborn. Now every time we use a bandage, the game kicks us out (but doesn't crash the server so there is no crash log exactly). 

Server side, we see this:

```
[20:30:50] [Netty Server IO #13/ERROR] [FML]: There was a critical exception handling a packet on channel firstaid
java.lang.NullPointerException: null
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:143) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) ~[SimpleNetworkWrapper.class:?]
	at ichttt.mods.firstaid.common.damagesystem.distribution.HealthDistribution.manageHealth(HealthDistribution.java:83) ~[HealthDistribution.class:?]
	at ichttt.mods.firstaid.common.damagesystem.distribution.HealthDistribution.distributeHealth(HealthDistribution.java:88) ~[HealthDistribution.class:?]
	at ichttt.mods.firstaid.common.EventHandler.onHeal(EventHandler.java:267) ~[EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1807_EventHandler_onHeal_LivingHealEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onLivingHeal(ForgeEventFactory.java:602) ~[ForgeEventFactory.class:?]
	at net.minecraft.entity.EntityLivingBase.heal(EntityLivingBase.java:835) ~[vp.class:?]
	at com.theundertaker11.geneticsreborn.api.capability.maxhealth.MaxHealth.onBonusMaxHealthChanged(MaxHealth.java:156) ~[MaxHealth.class:?]
	at com.theundertaker11.geneticsreborn.api.capability.maxhealth.MaxHealth.setBonusMaxHealth(MaxHealth.java:82) ~[MaxHealth.class:?]
	at com.theundertaker11.geneticsreborn.api.capability.maxhealth.MaxHealth.addBonusMaxHealth(MaxHealth.java:92) ~[MaxHealth.class:?]
	at com.theundertaker11.geneticsreborn.api.capability.maxhealth.MaxHealthStorage.readNBT(MaxHealthStorage.java:22) ~[MaxHealthStorage.class:?]
	at com.theundertaker11.geneticsreborn.api.capability.maxhealth.MaxHealthStorage.readNBT(MaxHealthStorage.java:9) ~[MaxHealthStorage.class:?]
	at com.theundertaker11.geneticsreborn.api.capability.maxhealth.MaxHealthCapabilityProvider.deserializeNBT(MaxHealthCapabilityProvider.java:37) ~[MaxHealthCapabilityProvider.class:?]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:135) ~[CapabilityDispatcher.class:?]
	at net.minecraft.entity.Entity.readFromNBT(Entity.java:1852) ~[vg.class:?]
	at net.minecraft.world.storage.SaveHandler.readPlayerData(SaveHandler.java:224) ~[bfb.class:?]
	at net.minecraft.server.management.PlayerList.readPlayerDataFromFile(PlayerList.java:324) ~[pl.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:116) ~[pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) ~[oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[20:30:50] [Netty Server IO #13/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated
```
Thanks for any help you can provide.

**Comment by ichttt** [comment]
Should be fixed in 1.6.13
