### ISSUE TITLE
[1.16.1]Crashes seem to occur whenever I fight mobs and a look at the crash report stated this mod to be the only problem

### ISSUE THREAD

**Issue by Silver073** [ichttt/FirstAid#94]
java.lang.NoSuchMethodError: net.minecraft.item.ArmorItem.getToughness()F
	at ichttt.mods.firstaid.common.util.ArmorUtils.applyArmor(ArmorUtils.java:108) ~[?:1.9.1] {re:classloading}
	at ichttt.mods.firstaid.common.damagesystem.distribution.DamageDistribution.distributeDamage(DamageDistribution.java:125) ~[?:1.9.1] {re:classloading}
	at ichttt.mods.firstaid.common.damagesystem.distribution.DamageDistribution.handleDamageTaken(DamageDistribution.java:66) ~[?:1.9.1] {re:classloading}
	at ichttt.mods.firstaid.common.EventHandler.onLivingHurt(EventHandler.java:123) ~[?:1.9.1] {re:classloading,pl:object_holder_definalize:A}
	at net.minecraftforge.eventbus.ASMEventHandler_85_EventHandler_onLivingHurt_LivingHurtEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:326) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70665_d(PlayerEntity.java:866) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:983) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_70097_a(PlayerEntity.java:809) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70097_a(ServerPlayerEntity.java:586) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70652_k(MobEntity.java:1344) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_190102_a(MeleeAttackGoal.java:138) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_75246_d(MeleeAttackGoal.java:130) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$6255/1232607635.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:681) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2410) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:487) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:42) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2157) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:299) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.monster.SpiderEntity.func_70071_h_(SpiderEntity.java:78) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:604) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld$$Lambda$6238/22569487.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:596) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:791) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:81) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5682/1580883724.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at ichttt.mods.firstaid.common.util.ArmorUtils.applyArmor(ArmorUtils.java:108)
	at ichttt.mods.firstaid.common.damagesystem.distribution.DamageDistribution.distributeDamage(DamageDistribution.java:125)
	at ichttt.mods.firstaid.common.damagesystem.distribution.DamageDistribution.handleDamageTaken(DamageDistribution.java:66)
	at ichttt.mods.firstaid.common.EventHandler.onLivingHurt(EventHandler.java:123)
	at net.minecraftforge.eventbus.ASMEventHandler_85_EventHandler_onLivingHurt_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:326)
	at net.minecraft.entity.player.PlayerEntity.func_70665_d(PlayerEntity.java:866)
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:983)
	at net.minecraft.entity.player.PlayerEntity.func_70097_a(PlayerEntity.java:809)
	at net.minecraft.entity.player.ServerPlayerEntity.func_70097_a(ServerPlayerEntity.java:586)
	at net.minecraft.entity.MobEntity.func_70652_k(MobEntity.java:1344)
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_190102_a(MeleeAttackGoal.java:138)
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_75246_d(MeleeAttackGoal.java:130)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
	at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$6255/1232607635.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:681)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2410)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:487)
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:42)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2157)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:299)
	at net.minecraft.entity.monster.SpiderEntity.func_70071_h_(SpiderEntity.java:78)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:604)
	at net.minecraft.world.server.ServerWorld$$Lambda$6238/22569487.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:spider (net.minecraft.entity.monster.SpiderEntity)
	Entity ID: 58
	Entity Name: Spider
	Entity's Exact location: -26.71, 67.00, -132.62
	Entity's Block location: World: (-27,67,-133), Chunk: (at 5,4,11 in -2,-9; contains blocks -32,0,-144 to -17,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.04, -0.08, 0.07
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:596)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['ElectrumKnight'/184, l='ServerLevel[Lag Test #2]', x=-27.52, y=67.00, z=-133.57]]
	Chunk stats: ServerChunkCache: 2108
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,63,-213), Chunk: (at 0,3,11 in -2,-14; contains blocks -32,0,-224 to -17,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 15346 game time, 15346 day time
	Level name: Lag Test #2
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 121608 (now: false), thunder time: 73404 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:791)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:81)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
	at net.minecraft.server.MinecraftServer$$Lambda$5682/1580883724.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2974002136 bytes (2836 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.65.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.65.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.65.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.65.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.16.1-32.0.65.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.65
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.65-client.jar Minecraft {minecraft@1.16.1 DONE}
		BedBenefits-1.16.1-1.0.1.jar BedBenefits {bedbenefits@1.0.1 DONE}
		theoneprobe-1.16-3.0.0-beta.jar The One Probe {theoneprobe@1.16-3.0.0-beta DONE}
		Ma-Enchants-1.16.1-3.2.1.jar Ma Enchants {ma-enchants@1.16.1-3.2.1 DONE}
		ToLaserBlade-1.16.1-3.1.4.0.jar ToLaserBlade {tolaserblade@1.16.1-3.1.4.0 DONE}
		dungeons-plus-1.16.1-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 DONE}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 DONE}
		tnt-yeeter-1.16.1-1.2.0.jar TNT Yeeter {yeeter@1.2.0 DONE}
		Abnormals-Core-1.16.1-v2.0.0.jar Abnormals Core {abnormals_core@2.0.0 DONE}
		Savage-and-Ravage-1.16.1-2.0.0.jar Savage & Ravage {savageandravage@2.0.0 DONE}
		Rotten+Flesh+to+Leather+1.16.1+-+1.0.1.jar Rotten Flesh to Leather {rftl@1.16.1 - 1.0.1 DONE}
		Waystones_1.16.1-7.0.1.jar Waystones {waystones@7.0.1 DONE}
		gravestone-1.16.1-1.0.3.jar Gravestone Mod {gravestone@1.16.1-1.0.3 DONE}
		collective-1.16.1-1.35.jar Collective {collective@1.35 DONE}
		FastWorkbench-1.16.1-4.1.1.jar FastWorkbench {fastbench@4.1.1 DONE}
		Placebo-1.16.1-4.0.1.jar Placebo {placebo@4.0.1 DONE}
		EnderBags-1.16.1-6.0.0.jar Ender Bags {ender_bags@6.0.0 DONE}
		gemsnjewels_1.16.1-0.5.2.jar Gems & Jewels {gemsnjewels@0.5.0 DONE}
		guardvillagers-1.16.1-1.1.0.jar Guard Villagers {guardvillagers@1.0.7 DONE}
		starterkit_1.16-1.0.jar Starter Kit {starterkit@1.0 DONE}
		FastFurnace-1.16.1-4.0.0.jar FastFurnace {fastfurnace@4.0.0 DONE}
		FpsReducer-mc1.16.1-1.16.jar FPS Reducer {fpsreducer@mc1.16.1-1.16 DONE}
		forgemod_VoxelMap-1.10.5b_for_1.16.1.jar VoxelMap {voxelmap@1.10.5 DONE}
		firstaid-1.9.1.jar First Aid {firstaid@1.9.1 DONE}
		forge-1.16.1-32.0.65-universal.jar Forge {forge@32.0.65 DONE}
		FastLeafDecay-v23.jar FastLeafDecay {fastleafdecay@v23 DONE}
		BetterMineshaftsForge-1.16.1-1.1.jar YUNG's Better Mineshafts {bettermineshafts@1.16.1-1.1 DONE}
		healingcf_1.16-2.3.jar Healing Campfire {healingcf@2.3 DONE}
		lumberjack-2.1.0.jar LumberJack {lumberjack@2.1.0 DONE}
		structure-gel-api-1.16.1-1.1.1.jar Structure Gel API {structure_gel@1.1.1 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['ElectrumKnight'/184, l='ServerLevel[Lag Test #2]', x=-27.52, y=67.00, z=-133.57]]
	Data Packs: vanilla, mod:abnormals_core, mod:bedbenefits (incompatible), mod:bettermineshafts, mod:collective, mod:dungeons_plus, mod:ender_bags (incompatible), mod:fastbench (incompatible), mod:fastfurnace (incompatible), mod:fastleafdecay, mod:firstaid (incompatible), mod:forge (incompatible), mod:fpsreducer, mod:gemsnjewels, mod:gravestone, mod:guardvillagers (incompatible), mod:healingcf, mod:jei (incompatible), mod:lumberjack (incompatible), mod:ma-enchants (incompatible), mod:placebo (incompatible), mod:rftl, mod:savageandravage, mod:starterkit, mod:structure_gel, mod:theoneprobe (incompatible), mod:tolaserblade, mod:voxelmap, mod:waystones (incompatible), mod:yeeter (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by ichttt** [comment]
For some strange reason, the method call is not being reobfuscated... I'll dig into it

**Comment by ichttt** [comment]
Fixed in FirstAid 1.9.2
